---
all:
  children:
    test:
      test_machines:
        hosts:
          testbox_01.local:
            ansible_host: 10.1.1.200
          testbox_02.local:
            ansible_host: 10.1.1.201
    production:
      prod_machines:
        hosts:
          prodbox_01.local:
            ansible_host: 10.1.1.210
          prodbox_02.local:
            ansible_host: 10.1.1.211
